apiVersion: v1
kind: Secret
metadata:
  name: whoop-david-api-secrets
  namespace: apptolast-whoop-david-api
  labels:
    app: whoop-david-api
type: Opaque
stringData:
  # Whoop OAuth2
  WHOOP_CLIENT_ID: "<CAMBIAR>"
  WHOOP_CLIENT_SECRET: "<CAMBIAR>"

  # Power BI Basic Auth
  POWERBI_USERNAME: "powerbi"
  POWERBI_PASSWORD: "<CAMBIAR>"

  # PostgreSQL
  DATABASE_URL: "jdbc:postgresql://postgresql.apptolast-whoop-david-api.svc.cluster.local:5432/whoop_david"
  DB_USERNAME: "whoopuser"
  DB_PASSWORD: "<CAMBIAR>"
