apiVersion: v1
kind: Service
metadata:
  name: whoop-david-api
  namespace: apptolast-whoop-david-api
  labels:
    app: whoop-david-api
spec:
  type: ClusterIP
  selector:
    app: whoop-david-api
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
