apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: whoop-david-api-ingress
  namespace: apptolast-whoop-david-api
  annotations:
    cert-manager.io/cluster-issuer: cloudflare-clusterissuer
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  ingressClassName: traefik
  rules:
    - host: david-whoop.apptolast.com
      http:
        paths:
          - backend:
              service:
                name: whoop-david-api
                port:
                  number: 8080
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - david-whoop.apptolast.com
      secretName: whoop-david-api-tls
